CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Accounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NULL,
    "Password" text NULL,
    "PhoneNumber" text NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
);

INSERT INTO "Accounts" ("Id", "Password", "PhoneNumber", "Username")
VALUES (1, 'pass', '+79123456789', 'firstUser');

SELECT setval(
    pg_get_serial_sequence('"Accounts"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Accounts") + 1,
        nextval(pg_get_serial_sequence('"Accounts"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230816132146_InitialMigration', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Accounts" DROP CONSTRAINT "PK_Accounts";

ALTER TABLE "Accounts" RENAME TO "Account";

ALTER TABLE "Account" ADD "Icon" bytea NULL;

ALTER TABLE "Account" ADD "Info" text NULL;

ALTER TABLE "Account" ADD CONSTRAINT "PK_Account" PRIMARY KEY ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231004080543_AddChannel', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Account" ADD "ChannelId" integer NULL;

CREATE TABLE "Channel" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Info" text NOT NULL,
    "InviteLink" text NOT NULL,
    "Icon" bytea NOT NULL,
    CONSTRAINT "PK_Channel" PRIMARY KEY ("Id")
);

CREATE TABLE "Posts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChannelId" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Text" text NOT NULL,
    CONSTRAINT "PK_Posts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Posts_Channel_ChannelId" FOREIGN KEY ("ChannelId") REFERENCES "Channel" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Account_ChannelId" ON "Account" ("ChannelId");

CREATE INDEX "IX_Posts_ChannelId" ON "Posts" ("ChannelId");

ALTER TABLE "Account" ADD CONSTRAINT "FK_Account_Channel_ChannelId" FOREIGN KEY ("ChannelId") REFERENCES "Channel" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240215142006_AddedPosts', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Posts" DROP CONSTRAINT "FK_Posts_Channel_ChannelId";

DROP TABLE "Account";

DROP TABLE "Channel";

DROP INDEX "IX_Posts_ChannelId";

ALTER TABLE "Posts" RENAME COLUMN "Text" TO "Message";

ALTER TABLE "Posts" RENAME COLUMN "Created" TO "Date";

ALTER TABLE "Posts" RENAME COLUMN "ChannelId" TO "PeerId";

CREATE TABLE "Channels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Info" text NOT NULL,
    "InviteLink" text NOT NULL,
    "Icon" bytea NOT NULL,
    CONSTRAINT "PK_Channels" PRIMARY KEY ("Id")
);

CREATE TABLE "Accounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NULL,
    "Password" text NULL,
    "PhoneNumber" text NULL,
    "Info" text NULL,
    "Icon" bytea NULL,
    "ChannelId" integer NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Accounts_Channels_ChannelId" FOREIGN KEY ("ChannelId") REFERENCES "Channels" ("Id")
);

INSERT INTO "Accounts" ("Id", "ChannelId", "Icon", "Info", "Password", "PhoneNumber", "Username")
VALUES (1, NULL, NULL, NULL, 'pass', '+79123456789', 'firstUser');

CREATE INDEX "IX_Accounts_ChannelId" ON "Accounts" ("ChannelId");

SELECT setval(
    pg_get_serial_sequence('"Accounts"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Accounts") + 1,
        nextval(pg_get_serial_sequence('"Accounts"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240222082024_ChangeModels', '6.0.21');

COMMIT;

START TRANSACTION;

DELETE FROM "Accounts"
WHERE "Id" = 1;

ALTER TABLE "Channels" DROP COLUMN "Icon";

ALTER TABLE "Channels" DROP COLUMN "Info";

ALTER TABLE "Accounts" DROP COLUMN "Icon";

ALTER TABLE "Accounts" DROP COLUMN "Info";

ALTER TABLE "Channels" RENAME COLUMN "Name" TO "Title";

ALTER TABLE "Channels" RENAME COLUMN "InviteLink" TO "MainUsername";

ALTER TABLE "Accounts" RENAME COLUMN "PhoneNumber" TO "Name";

ALTER TABLE "Accounts" RENAME COLUMN "Password" TO "Bio";

ALTER TABLE "Channels" ADD "IsChannel" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Channels" ADD "IsGroup" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NULL,
    "Password" text NULL,
    "PhoneNumber" text NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "Users" ("Id", "Password", "PhoneNumber", "Username")
VALUES (1, 'pass', '+79123456789', 'firstUser');

SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240222113622_AddPosts', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Channels" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "Accounts" ALTER COLUMN "ChannelId" TYPE bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240301092741_ChannelIdToLong', '6.0.21');

COMMIT;

START TRANSACTION;

DELETE FROM "Users"
WHERE "Id" = 1;

ALTER TABLE "Users" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "Posts" ALTER COLUMN "PeerId" TYPE bigint;

ALTER TABLE "Posts" ALTER COLUMN "Id" TYPE bigint;

ALTER TABLE "Channels" ALTER COLUMN "Title" DROP NOT NULL;

ALTER TABLE "Channels" ALTER COLUMN "MainUsername" DROP NOT NULL;

ALTER TABLE "Channels" ADD "UserId" bigint NULL;

ALTER TABLE "Accounts" ALTER COLUMN "Id" TYPE bigint;

INSERT INTO "Users" ("Id", "Password", "PhoneNumber", "Username")
VALUES (1, 'pass', '+79123456789', 'firstUser');

CREATE INDEX "IX_Channels_UserId" ON "Channels" ("UserId");

ALTER TABLE "Channels" ADD CONSTRAINT "FK_Channels_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240301111407_AllIdsToLong', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" RENAME COLUMN "Id" TO "UserId";

ALTER TABLE "Posts" RENAME COLUMN "Id" TO "PostId";

ALTER TABLE "Channels" RENAME COLUMN "Id" TO "ChannelId";

ALTER TABLE "Accounts" RENAME COLUMN "Username" TO "AccountName";

ALTER TABLE "Accounts" RENAME COLUMN "Id" TO "AccountId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240719092704_RenameTablesAndIdColumns', '6.0.21');

COMMIT;

START TRANSACTION;

ALTER TABLE "Channels" RENAME COLUMN "ChannelId" TO "Id";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240719112803_ReturnChannelIdColumnName', '6.0.21');

COMMIT;

