version: "3.8"

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/console_templates"
            - "--storage.tsdb.retention.time=200h"
            - "--web.enable-lifecycle"
        networks:
            - monitoring

    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - "3100:3100"
        volumes:
            - ./loki-config.yml:/etc/loki/local-config.yml
            - loki_data:/loki
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - monitoring

    promtail:
        image: grafana/promtail:latest
        container_name: promtail
        ports:
            - "9080:9080"
        volumes:
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yml
        networks:
            - monitoring

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            # - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
            # - GF_AUTH_ANONYMOUS_ENABLED=true
            # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            # - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
            - grafana_data:/var/lib/grafana
        # entrypoint:
        #     - sh
        #     - -euc
        #     - |
        #         mkdir -p /etc/grafana/provisioning/datasources
        #         cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        #         apiVersion: 1
        #         datasources:
        #         - name: Loki
        #           type: loki
        #           access: proxy
        #           orgId: 1
        #           url: http://loki:3100
        #           basicAuth: false
        #           isDefault: true
        #           version: 1
        #           editable: false
        #         EOF
        #         /run.sh
        networks:
            - monitoring
        depends_on:
            - prometheus
            - loki
            - promtail

volumes:
    prometheus_data:
    loki_data:
    grafana_data:

networks:
    monitoring:
        driver: bridge
